CREATE TABLE `products` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`barcode` text NOT NULL UNIQUE,
	`name` text NOT NULL,
	`brands` text,
	`search_name` text NOT NULL,
	`search_brands` text NOT NULL,
	`package_quantity` text,
	`serving_size` text,
	`energy_kcal_100g` real NOT NULL,
	`energy_kj_100g` real,
	`fat_100g` real NOT NULL,
	`saturated_fat_100g` real,
	`carbohydrates_100g` real NOT NULL,
	`sugars_100g` real,
	`fiber_100g` real,
	`protein_100g` real NOT NULL,
	`salt_100g` real,
	`sodium_100g` real,
	`countries` text NOT NULL,
	`categories` text NOT NULL,
	`allergens` text NOT NULL,
	`traces` text NOT NULL,
	`data_quality_errors` text NOT NULL,
	`image_url` text,
	`thumbnail_url` text,
	`source_url` text NOT NULL,
	`source_modified_at` integer NOT NULL
);
