import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

const [apiUrlArgument, outputPath] = process.argv.slice(2);

if (apiUrlArgument === undefined || outputPath === undefined) {
  throw new Error("usage: write-proxy.mjs <api-preview-url> <output-path>");
}

const apiUrl = new URL(apiUrlArgument);
if (
  apiUrl.protocol !== "https:" ||
  !apiUrl.hostname.endsWith(".workers.dev") ||
  apiUrl.pathname !== "/" ||
  apiUrl.search !== "" ||
  apiUrl.hash !== ""
) {
  throw new Error("the API preview URL must be an https://*.workers.dev origin");
}

const source = `// Generated by tools/cloudflare-preview/write-proxy.mjs. Do not edit.
const apiOrigin = ${JSON.stringify(apiUrl.origin)};

const isApiRequest = (pathname) =>
  pathname === "/trpc" ||
  pathname.startsWith("/trpc/") ||
  pathname === "/api/auth" ||
  pathname.startsWith("/api/auth/") ||
  pathname === "/health";

export default {
  async fetch(request, env) {
    const publicUrl = new URL(request.url);
    if (!isApiRequest(publicUrl.pathname)) return env.ASSETS.fetch(request);

    const targetUrl = new URL(publicUrl.pathname + publicUrl.search, apiOrigin);
    const headers = new Headers(request.headers);
    // The browser talks to Pages on the same origin. Present the server-to-server
    // hop as same-origin too, rather than trusting every pages.dev hostname in the API.
    headers.set("origin", apiOrigin);
    headers.delete("host");

    const upstream = await fetch(new Request(targetUrl, { method: request.method, headers, body: request.body, redirect: "manual" }));
    const responseHeaders = new Headers(upstream.headers);
    const location = responseHeaders.get("location");
    if (location?.startsWith(apiOrigin)) {
      responseHeaders.set("location", publicUrl.origin + location.slice(apiOrigin.length));
    }
    return new Response(upstream.body, { status: upstream.status, statusText: upstream.statusText, headers: responseHeaders });
  },
};
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
