/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1afb4bd66733e4a077fea8b949c2a0a2)
interface __BaseEnv_Env {
	FOOD_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
