/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0760d623d841b02c85946928d17cb37a)
interface __BaseEnv_Env {
	FOOD_DB: D1Database;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
